name: Trigger auto deployment for container-app-cd3oximukelci

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '.devcontainer/**'
    - '.github/workflows/container-app-cd3oximukelci-AutoDeployTrigger-2653d627-ea2a-4b53-9ee6-c2045246bfae.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrycd3oximukelci.azurecr.io
          username: ${{ secrets.CONTAINERAPPCD3OXIMUKELCI_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPCD3OXIMUKELCI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrycd3oximukelci.azurecr.io/container-app-cd3oximukelci:${{ github.sha }}
          file: ./.devcontainer/Dockerfile
          context: ./.devcontainer/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPCD3OXIMUKELCI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPCD3OXIMUKELCI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPCD3OXIMUKELCI_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-cd3oximukelci -g todojavamongowoa22d --server containerregistrycd3oximukelci.azurecr.io --username  ${{ secrets.CONTAINERAPPCD3OXIMUKELCI_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPCD3OXIMUKELCI_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-cd3oximukelci -g todojavamongowoa22d --image containerregistrycd3oximukelci.azurecr.io/container-app-cd3oximukelci:${{ github.sha }}
